# Generated by Django 5.2.7 on 2025-10-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_page_image"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="chapter",
            new_name="core_chapte_comic_i_e881ad_idx",
            old_name="core_chap_comic_i_8371f8_idx",
        ),
        migrations.RenameIndex(
            model_name="comic",
            new_name="core_comic_created_b2a0d7_idx",
            old_name="core_comi_created_83545c_idx",
        ),
        migrations.RenameIndex(
            model_name="comic",
            new_name="core_comic_status_e2bb66_idx",
            old_name="core_comi_status_a71a98_idx",
        ),
        migrations.RenameIndex(
            model_name="readinghistory",
            new_name="core_readin_user_id_fc79c3_idx",
            old_name="core_read_user_id_4d0347_idx",
        ),
    ]
