# Generated by Django 5.2.7 on 2025-11-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_core_chap_comic_i_8371f8_idx_core_chapte_comic_i_e881ad_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
